### PR TITLE
VCS segments - Bazaar and Fossil

### PR DESCRIPTION
**Pull request by emansije**
Adds a segment for Bazaar and another for Fossil.

### CODE REVIEW

**Comment by justjanne** [comment]
Looks good so far, but it seems you’ve broken the markdown formatting in README.md (note that two spaces at the end of a line are interpreted as `<br>` by markdown)

**Comment by emansije** [comment]
> Looks good so far, but it seems you’ve broken the markdown formatting in README.md (note that two spaces at the end of a line are interpreted as `<br>` by markdown).

Oops! Sorry! The editor I used had an option enabled to trim white space at the end of the line, when saving the file, and I didn't notice it when checking the diffs before committing.

> Please try to fix that, and I’ll be able to merge the PR

There have been a few commits in the meanwhile. Would it be better if I merged those commits into my branch and did a new PR, instead of fixing this one?

**Comment by justjanne** [comment]
Sorry for the delay, if you could please rebase this branch I’ll be able to merge it for v1.21.0 :)

**Comment by emansije** [comment]
A lot has changed since I created this PR and it became a bit of a mess to rebase it (my git-fu wasn't strong enough, I suppose), so I just made a new PR (#274) to replace this one. Sorry for the inconvenience.

**Pull request closed without merging**
