### PR TITLE
minor changes to support hostname colorization via env vars

### PR DESCRIPTION
**Pull request by wynnw**

### CODE REVIEW

**Comment by justjanne** [comment]
Could you split the gruvbox theme into a separate PR? Thanks :)

**Comment by zoj613** [comment]
this gruvbox theme does not work on my xtce4-terminal

**Comment by wynnw** [comment]
Do you mean xfce4 ? Can you provide more details?

**Comment by zoj613** [comment]
> Do you mean xfce4 ? Can you provide more details?

it worked after I manually installed powerline-go instead of using the old binary. Its not part of release 1.17

**Comment by wynnw** [comment]
Yes - I saw the same thing. The 1.17 release binary doesn't work for this theme. If I build it manually from the master branch then it works fine. Not sure what broke there.

**Comment by zoj613** [comment]
> Yes - I saw the same thing. The 1.17 release binary doesn't work for this theme. If I build it manually from the master branch then it works fine. Not sure what broke there.

I think the commit adding the theme wasn't part of the binary build.

**Pull request closed without merging**
