### PR TITLE
Add config file support

### PR DESCRIPTION
**Pull request by cjvaughter**
### What this does
This enables settings to be loaded from `~/.config/powerline-go/config.json` in addition to the usual arguments.

### How it works
This refactors everything configuration related into a `Config` struct. This struct is initialized with default values, loaded from `config.json`, then any `args` provided override their config counterparts. This should provide a seamless transition, as existing usage is preserved.

Each setting uses the equivalent arg name, with the exception of error and duration (which can only be set via args, as setting them in config would make no sense).

There are a few special settings:
- `modes`, `themes`, and `shells` do not completely override the defaults, only add values to their respective maps.
- `modes` and `themes` work exactly like loading them from an external file (i.e. they are preloaded with defaults so you don't have to specify the whole thing). 
- `path-aliases` specified via args are added to ones specified via config.

### Example
Here is my `config.json`: (ignore the unicode shenanigans)
```json
{
    "modules": [ "user", "cwd" ,"perms", "git", "jobs", "root" ],
    "path-aliases":
    {
       "~": "🏠",
       "~/github/powerline-go": "🔌"
    },
    "theme": "wsl",
    "themes":
    {
        "wsl":
        {
            "RepoCleanFg": 15,
            "RepoCleanBg": 22,
            "RepoDirtyFg": 15,
            "RepoDirtyBg": 130
        }
    },
    "mode": "wsl",
    "modes":
    {
        "wsl":
        {
            "Lock":             "🔒",
            "Network":          "🚀",
            "RepoDetached":     "⚓",
            "RepoAhead":        "🔺",
            "RepoBehind":       "🔻",
            "RepoStaged":       "✔\uFE0F",
            "RepoNotStaged":    "✏\uFE0F",
            "RepoUntracked":    "➕",
            "RepoConflicted":   "❄\uFE0F",
            "RepoStashed":      "🎁"
        }
    }
}
```
Prompt: ```PS1="$(powerline-go -error $?)"```

### Other thoughts
- The performance impact is pretty negligible. On my machine I measured ~500-600ns to load the config. When no config file exists, there is practically no difference.
- We could potentially allow specifying the config location.
- I was torn on whether or not to merge arg specified `ignore-repos` with config ones (like `path-aliases`). This can easily be done if you'd like.
- I don't like having two data structures that need to be manually kept in sync, but I wasn't sure how else to do it. Mostly due to the way the flag system works.

Let me know if you have any questions.

### CODE REVIEW

**Review by justjanne — APPROVED** [review]

**Comment by justjanne** [comment]
Please rebase so I can merge :)

**Comment by cjvaughter** [comment]
Okay, now this should be ready after merging #247.

**Comment by cjvaughter** [comment]
Well, I was wrong. 😅
**Now** it's ready.

**Comment by cjvaughter** [comment]
Now it's _really_ ready (you've been quite active today!)

**Comment by justjanne** [comment]
You were just a tiny bit faster than me just now, I just got a complaint from GitHub "this page is out of date, please reload" while resolving the conflicts :)

**Comment by justjanne** [comment]
> Now it's _really_ ready (you've been quite active today!)

Yeah after I saw just how much this project has grown recently (and it's now even in official Windows documentation on microsoft.com :open_mouth:), I decided I really need to clean this up and fix many of the outstanding issues :)

**Comment by cjvaughter** [comment]
I knew I'd be ahead eventually, lol.

Well I'm glad, this is a great project!

**Pull request merged**
