### PR TITLE
First stab at a theme for light background terminals

### PR DESCRIPTION
**Pull request by autarch**
I haven't tested out every possible segment, but for the ones I can easily
test this is a much better set of colors if your terminal background is white
rather than black.

### CODE REVIEW

**Comment by justjanne** [comment]
This looks great, although it seems like the Home and the Root segment have an entirely transparent background?

**Comment by autarch** [comment]
Give me a little time to fine tune it. There's a couple spots where the colors don't work so well. Notably, the separate between the username and hostname segments is invisible because of poor color choices.

**Comment by justjanne** [comment]
Sure, don’t worry. I already like your theme :+1:

**Comment by autarch** [comment]
Alright, I spent some more time on this and I think it's ready for a merge. I renamed it from "light" to "low-contrast" since that's really what this theme is about. Thanks for your work on powerline!

**Comment by justjanne** [comment]
Looks fine to me:

Screenshot of light theme

**Pull request merged**
